In [16]:
import pickle as pkl
import numpy as np
from sklearn import metrics

In [9]:
len_features = 5000

with open('../data/tfidf{}_test.pkl'.format(len_features), 'rb') as f:
    tfidf = pkl.load(f)
y = np.load('../data/y_test.npy')
assert tfidf.shape[0] == y.shape[0]

Naive Bayes

In [11]:
scores = np.load('../data/NBscores_5000.npy')

In [13]:
y_pred = []
for doc in tfidf:
    doc = doc.toarray().flatten()
    tmp = scores.dot(doc)
    y_pred.append(tmp.argmax())

In [17]:
print(metrics.accuracy_score(y, y_pred))

0.876735


In [18]:
print(metrics.confusion_matrix(y, y_pred))

[[36100   618   780   347   393   724   109   706    50   173]
 [  181 36366  1294   569   306    40   272   342    80   550]
 [  440  1132 34358   942   391   433   486   501   381   936]
 [  169   380   829 36125   859    25   169  1149   124   171]
 [  199   267   622  1280 33481   471   175  2329   712   464]
 [ 1054    89  1273   145   583 34547   108   873   755   573]
 [   42   192   546   149    71    20 37958   453   247   322]
 [  326   351   394   948  1797   133   985 33431  1111   524]
 [   66   136   729   143   455   406   737   464 35959   905]
 [  236   561  1163   408   637   502  1299  1425  1400 32369]]


LinerSVC

In [19]:
with open('../data/linersvm5000.pkl', 'rb') as f:
    clf = pkl.load(f)

In [20]:
y_pred = clf.predict(tfidf)

In [21]:
print(metrics.accuracy_score(y, y_pred))

0.9090875


In [22]:
print(metrics.confusion_matrix(y, y_pred))

[[37524   366   533   133   204   641    32   397    59   111]
 [  194 37566   872   277   184    59   101   308   105   334]
 [  513   652 35415   488   320   723   366   441   352   730]
 [  228   244   783 36626   754    71    78   939   126   151]
 [  258   174   514   768 34904   337    88  2091   528   338]
 [  563    37   603    74   353 36909    37   455   531   438]
 [   57    90   369    71    81    37 38135   497   337   326]
 [  399   278   475   609  1276   285   384 34828   881   585]
 [   69    63   446    97   383   386   276   533 37059   688]
 [  202   343  1052   193   442   380   419  1156  1144 34669]]
