In [15]:
import pickle as pkl
import numpy as np
from sklearn import metrics

In [4]:
len_features = 5000

with open('../data/tfidf{}_test.pkl'.format(len_features), 'rb') as f:
    tfidf = pkl.load(f)
y = np.load('../data/y_test.npy')
assert tfidf.shape[0] == y.shape[0]

In [14]:
catagorys = ['agriculture', 'car', 'computersoftware', 'finance', 'labor',
             'medical', 'movie', 'policy', 'psychology', 'sport']
def score(ret):
    """
    计算每个类的precision，recell，F1
    :param ret: 整体的混淆矩阵
    :return:
    """
    for i in range(ret.shape[0]):
        TP = ret[i][i]
        FN = ret[i].sum() - ret[i][i]
        FP = ret[:, i].sum() - ret[i][i]
        TN = ret.sum() - TP - FN - FP
        precision = TP/(TP+FP)
        recall = TP/(TP+FN)
        f1_score = 2*TP/(ret.sum() + TP - TN)
        print('\nmetric of {}:'.format(catagorys[i]))
        print('confusion_matrix\n[[{}, {}],\n[{}, {}]]'.format(TP, FN, FP, TN))
        print('precision={}, recall={}, f1_score={}'.format(precision, recall, f1_score))

Naive Bayes

In [6]:
scores = np.load('../data/NBscores_5000.npy')

In [7]:
y_pred = []
for doc in tfidf:
    doc = doc.toarray().flatten()
    tmp = scores.dot(doc)
    y_pred.append(tmp.argmax())

In [8]:
print(metrics.accuracy_score(y, y_pred))

0.876735


In [9]:
print(metrics.confusion_matrix(y, y_pred))

[[36100   618   780   347   393   724   109   706    50   173]
 [  181 36366  1294   569   306    40   272   342    80   550]
 [  440  1132 34358   942   391   433   486   501   381   936]
 [  169   380   829 36125   859    25   169  1149   124   171]
 [  199   267   622  1280 33481   471   175  2329   712   464]
 [ 1054    89  1273   145   583 34547   108   873   755   573]
 [   42   192   546   149    71    20 37958   453   247   322]
 [  326   351   394   948  1797   133   985 33431  1111   524]
 [   66   136   729   143   455   406   737   464 35959   905]
 [  236   561  1163   408   637   502  1299  1425  1400 32369]]


In [16]:
score(metrics.confusion_matrix(y, y_pred))


metric of agriculture:
confusion_matrix
[[36100, 3900],
[2713, 357287]]
precision=0.9301007394429701, recall=0.9025, f1_score=0.9160925228071511

metric of car:
confusion_matrix
[[36366, 3634],
[3726, 356274]]
precision=0.9070637533672553, recall=0.90915, f1_score=0.9081056784697598

metric of computersoftware:
confusion_matrix
[[34358, 5642],
[7630, 352370]]
precision=0.8182814137372583, recall=0.85895, f1_score=0.8381226520954286

metric of finance:
confusion_matrix
[[36125, 3875],
[4931, 355069]]
precision=0.8798957521434139, recall=0.903125, f1_score=0.8913590604026845

metric of labor:
confusion_matrix
[[33481, 6519],
[5492, 354508]]
precision=0.8590819285146127, recall=0.837025, f1_score=0.8479100452053233

metric of medical:
confusion_matrix
[[34547, 5453],
[2754, 357246]]
precision=0.9261681992439881, recall=0.863675, f1_score=0.8938306102120283

metric of movie:
confusion_matrix
[[37958, 2042],
[4340, 355660]]
precision=0.8973946758711996, recall=0.94895, f1_score=0.922452550

LinerSVC

In [17]:
with open('../data/linersvm5000.pkl', 'rb') as f:
    clf = pkl.load(f)

In [18]:
y_pred = clf.predict(tfidf)

In [19]:
print(metrics.accuracy_score(y, y_pred))

0.9090875


In [20]:
print(metrics.confusion_matrix(y, y_pred))

[[37524   366   533   133   204   641    32   397    59   111]
 [  194 37566   872   277   184    59   101   308   105   334]
 [  513   652 35415   488   320   723   366   441   352   730]
 [  228   244   783 36626   754    71    78   939   126   151]
 [  258   174   514   768 34904   337    88  2091   528   338]
 [  563    37   603    74   353 36909    37   455   531   438]
 [   57    90   369    71    81    37 38135   497   337   326]
 [  399   278   475   609  1276   285   384 34828   881   585]
 [   69    63   446    97   383   386   276   533 37059   688]
 [  202   343  1052   193   442   380   419  1156  1144 34669]]


In [21]:
score(metrics.confusion_matrix(y, y_pred))


metric of agriculture:
confusion_matrix
[[37524, 2476],
[2483, 357517]]
precision=0.9379358612242857, recall=0.9381, f1_score=0.9380179234316998

metric of car:
confusion_matrix
[[37566, 2434],
[2247, 357753]]
precision=0.9435611483686233, recall=0.93915, f1_score=0.94135040657537

metric of computersoftware:
confusion_matrix
[[35415, 4585],
[5647, 354353]]
precision=0.8624762554186353, recall=0.885375, f1_score=0.8737756285312477

metric of finance:
confusion_matrix
[[36626, 3374],
[2710, 357290]]
precision=0.9311063656701241, recall=0.91565, f1_score=0.9233135020671575

metric of labor:
confusion_matrix
[[34904, 5096],
[3997, 356003]]
precision=0.8972519986632734, recall=0.8726, f1_score=0.8847543123661297

metric of medical:
confusion_matrix
[[36909, 3091],
[2919, 357081]]
precision=0.9267098523651702, recall=0.922725, f1_score=0.9247131332364584

metric of movie:
confusion_matrix
[[38135, 1865],
[1781, 358219]]
precision=0.9553813007315363, recall=0.953375, f1_score=0.954377095950

SVC(kernel='rbf', C=1000)

In [22]:
with open('../data/svm5000_c1000.pkl', 'rb') as f:
    clf = pkl.load(f)

d:\python36\lib\site-packages\sklearn\base.py:251: UserWarning: Trying to unpickle estimator SVC from version 0.20.1 when using version 0.20.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [ ]:
y_pred = clf.predict(tfidf)